---
galaxy_info:
  author: Alexei Znamensky, Markus Weippert
  description: Initialization for community.openwrt
  license: GPL-3.0-or-later
  min_ansible_version: '2.17'
  platforms:
    - name: OpenWrt
  galaxy_tags:
    - openwrt
    - networking
    - router
dependencies:
  - role: community.openwrt.common
