---
# Copyright (c) 2017 Markus Weippert
# GNU General Public License v3.0 (see https://www.gnu.org/licenses/gpl-3.0.txt)

DOCUMENTATION:
  module: service
  short_description: Manage services on OpenWrt targets
  description:
    - The M(community.openwrt.service) module controls services on OpenWrt using init scripts.
    - It can start, stop, restart, reload services and manage their enabled state.
  author: Markus Weippert (@gekmihesg)
  options:
    name:
      description:
        - Name of the service.
        - Corresponds to the init script name in C(/etc/init.d/).
      type: str
      required: true
    state:
      description:
        - Desired state of the service.
      type: str
      choices:
        - reloaded
        - restarted
        - started
        - stopped
    enabled:
      description:
        - Whether the service should start on boot.
      type: bool
    pattern:
      description:
        - Pattern to search for in the process table to determine if the service is running.
        - If specified, this pattern is used with C(pgrep) instead of the init script's running command.
      type: str
  notes:
    - This module is designed for OpenWrt devices without Python installed.
  supports_check_mode: true

EXAMPLES: |

RETURN:
